main: fr.enderstevegamer.fightforlobster.Main
name: FightForLobster
version: 1.0
author: Endersteve_gamer
api-version: 1.19
description: The plugin used for the "Fight For Lobster" minigame on my Minecraft server
commands:
  giverole:
    description: Gives a role to a player
    usage: /giverole <playerName> <roleName>
    aliases: gr
  giveroleitem:
    description: Gives the items of a role to a player
    usage: /giveroleitem <playerName> <roleName>
    aliases: gri
  selectrole:
    description: Opens the role selection menu
    usage: /selectrole
    aliases: sr